name: Build

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: ["38", "39", "40", "rawhide" ]
    steps:
      - uses: actions/checkout@v4
      - name: set fedora base docker version
        run: |
          sed -i -e "s|\$VERSION|${{ matrix.version }}|g" Dockerfile
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: "Dockerfile"
          push: true
          tags: "rubemlrm/fedora-ansible:${{ matrix.version }}"
          labels: ${{ matrix.version }}
